### ISSUE TITLE
Option to remove helper comments

### ISSUE THREAD

**Issue by mrd333** [popcodeorg/popcode#1423] opened 2018-04-12 16:33 UTC
Enjoying Popcode more and more all the time.  One more suggestion: the ability to turn off code error comments.  I do some debugging exercises that require students to hunt down the errors...obviously, this helpful feature in Popcode doesn't work with this type of exercise.

Thanks!

**Comment by mrd333** [comment] 2018-04-12 18:07
Absolutely, this sounds just about right!

Thanks again for all the hard work!

**Comment by outoftime** [comment] 2020-08-23 18:53
Closing as duplicate of #268

**Closed by outoftime** 2020-08-23 18:53 UTC
