### ISSUE TITLE
Loading Bootstrap without first loading jQuery doesn't work

### ISSUE THREAD

**Issue by inlinestyle** [popcodeorg/popcode#850] opened 2017-06-03 19:02 UTC
This gets logged to the console: 
![image](https://cloud.githubusercontent.com/assets/1098749/26756316/5c993e64-486d-11e7-941c-bd8bc5114f84.png)
Possible solutions:
- Automatically adding jQuery to the list of included libs when including Bootstrap
- Throwing up a warning if student tries to include Bootstrap without including jQuery (possibly with a button to include jQuery).

**Comment by outoftime** [comment] 2017-06-03 19:02
whoa-ho!

**Comment by GabiOC** [comment] 2017-06-24 22:01
Hi @inlinestyle @outoftime , I don't think we've met but I'm a volunteer at YCDHS and would like to start contributing to Popcode! I was thinking about starting with this but wanted to get some feedback about a possible alternative solution, kinda combining the two @inlinestyle suggested, before I get started.

If a student tries to include Bootstrap without including jQuery, we could automatically load jQuery and mark it as an included library in the dashboard, but also show a tooltip next to the jQuery library item saying something like 'jQuery was added because it's required for Bootstrap to work'. I think there's value in showing the dependencies between libraries while still streamlining the project set-up process but totally open to one of the original solutions proposed / another alternative!

**Comment by inlinestyle** [comment] 2017-06-25 15:23
Hi @GabiOC, I don't speak for @outoftime but I think this is a great starter project!

**Comment by outoftime** [comment] 2017-06-25 15:26
Hi! I _do_ speak for @outoftime and I agree with @inlinestyle . I’m curious to hear more about the “ tooltip next to the jQuery library item”—I presume this would be a new UI component? Would it appear on hover or always?

Would it be possible to disable jQuery as long as Bootstrap was enabled?

**Comment by GabiOC** [comment] 2017-06-25 17:49
Hey @outoftime , I think it'd be its own component for reusability and appear on click of the Bootstrap library item only if jQuery hadn't already been selected. I think it could be dismissable by a close button and/or on close of the side nav/library submenu.

We couldn't really disable jQuery while Bootstrap is still enabled, so if a student tries to do that, we'd probably need another tooltip pointing to the Bootstrap library item to make it clear that the student needs to disable it before they can disable jQuery.

**Comment by outoftime** [comment] 2017-06-25 19:01
@GabiOC OK—I’m not sure that I’m totally able to visualize what you have in mind, but I’m excited to see what you come up with!

**Comment by outoftime** [comment] 2017-07-13 13:36
Update on this—as it turns out Bootstrap’s JS doesn’t work in Popcode **even if you do enable jQuery** because Bootstrap’s JS is loaded on the page first. This might be a recent regression?

Anyway my inclination at this point is to just do the simplest possible thing—automatically load jQuery if you enable Bootstrap, and make sure jQuery is loaded before Bootstrap’s JS. Note that this would only affect the actual behavior of the generated page; jQuery would not be automatically *enabled* in the UI. The student also would not be able to directly use jQuery because the linter would consider `$` undefined. So I think that’s a pretty reasonable fix, although I’m definitely down for something that makes it more explicit in the future.

**Comment by outoftime** [comment] 2017-07-14 19:18
Per the above I did this: https://github.com/popcodeorg/popcode/pull/936

Check the PR description for all the sordid details!

I’m going to leave this open to continue the discussion over whether we should do something more explicit

**Comment by outoftime** [comment] 2017-12-18 03:06
Doesn’t seem like there’s much appetite for something more explicit. Fixed by #936

**Closed by outoftime** 2017-12-18 03:06 UTC
Labels: bug
